version: "3.3"
   
services:
  backend:
    container_name: backend
    build:
      context: ./core
      dockerfile: Dockerfile
    command: /venv/bin/gunicorn core.wsgi --bind 0.0.0.0:8000 --timeout 300
    volumes:
      - static:/backend/static #after static folder create - fill static_files volume
      - media:/backend/media #after static folder create - fill static_files volume
    ports:
      - "8000:8000"
  postgres:
    container_name: postgres-db
    image: postgres:9.6
    ports:
      - 5432:5432 # Bind host port 5432 to PostgreSQL port 5432
    volumes:
      - ./postgredb:/var/lib/postgresql/data
    env_file: ./core/.env
  nginx:
    image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static:/var/www/backend/static
      - media:/var/www/backend/media
    depends_on:
      - backend

