# Generated by Django 3.1.5 on 2021-04-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurCLients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_image', models.ImageField(upload_to='clients/')),
                ('client_title', models.CharField(max_length=200)),
                ('client_description', models.CharField(max_length=200)),
                ('client_context', models.TextField()),
            ],
        ),
    ]
