# Generated by Django 3.1.5 on 2021-04-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourclientpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourclients',
            name='client_context_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ourclients',
            name='client_context_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ourclients',
            name='client_context_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ourclients',
            name='client_description_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ourclients',
            name='client_description_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ourclients',
            name='client_description_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ourclients',
            name='client_title_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ourclients',
            name='client_title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ourclients',
            name='client_title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
