# Generated by Django 3.1.5 on 2021-04-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=True, upload_to='news/'),
            preserve_default=False,
        ),
    ]
