# Generated by Django 3.1.5 on 2021-04-30 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspage', '0003_auto_20210419_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Yeniliklerimiz'},
        ),
    ]
