# Generated by Django 3.1.5 on 2021-04-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.URLField(verbose_name='facebook linki')),
            ],
            options={
                'verbose_name_plural': 'Facebook Link',
            },
        ),
    ]
