# Generated by Django 3.1.5 on 2021-04-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0002_facebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(verbose_name='Niyə bizi seçmələri üçün səbəb')),
            ],
            options={
                'verbose_name_plural': 'Niyə biz',
            },
        ),
    ]
