# Generated by Django 3.1.5 on 2021-04-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0003_chooseus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_link', models.URLField(verbose_name='instagram linki')),
            ],
            options={
                'verbose_name_plural': 'Instagram Link',
            },
        ),
        migrations.CreateModel(
            name='LinkedIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_link', models.URLField(verbose_name='LinkedIn linki')),
            ],
            options={
                'verbose_name_plural': 'LinkedIn Link',
            },
        ),
        migrations.CreateModel(
            name='SubscribedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Yeniliklerden xeberdar olmaq isteyenler',
            },
        ),
        migrations.CreateModel(
            name='Whatsapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_link', models.URLField(verbose_name='whatsapp linki')),
            ],
            options={
                'verbose_name_plural': 'Whatsapp Link',
            },
        ),
        migrations.AlterField(
            model_name='chooseus',
            name='context',
            field=models.TextField(blank=True, null=True, verbose_name='Niyə bizi seçmələri üçün səbəb'),
        ),
    ]
