# Generated by Django 3.1.5 on 2021-04-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0004_auto_20210415_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='chooseus',
            name='context_az',
            field=models.TextField(blank=True, null=True, verbose_name='Niyə bizi seçmələri üçün səbəb'),
        ),
        migrations.AddField(
            model_name='chooseus',
            name='context_en',
            field=models.TextField(blank=True, null=True, verbose_name='Niyə bizi seçmələri üçün səbəb'),
        ),
        migrations.AddField(
            model_name='chooseus',
            name='context_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Niyə bizi seçmələri üçün səbəb'),
        ),
    ]
