# Generated by Django 3.1.5 on 2021-04-30 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0005_auto_20210419_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name_plural': 'Kontakt Info'},
        ),
    ]
