# Generated by Django 3.1.5 on 2021-04-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='slides/', verbose_name='Slayd şəkli')),
            ],
            options={
                'verbose_name_plural': 'Slayd şəkilləri',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ManyToManyField(blank=True, to='homepage.SlideImages', verbose_name='slayd şəkilləri')),
            ],
            options={
                'verbose_name_plural': 'Slayd',
            },
        ),
    ]
