# Generated by Django 3.1.5 on 2021-04-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='button_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='slide',
            name='button_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Linkin adı'),
        ),
        migrations.RemoveField(
            model_name='slide',
            name='image',
        ),
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, upload_to='slides/', verbose_name='Slayd şəkli'),
        ),
        migrations.DeleteModel(
            name='SlideImages',
        ),
    ]
