# Generated by Django 3.1.5 on 2021-04-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20210415_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='button_link',
            field=models.URLField(verbose_name='Link'),
        ),
    ]
