# Generated by Django 3.1.5 on 2021-04-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='context',
            field=models.TextField(blank=True, null=True, verbose_name='Slayd mətni'),
        ),
    ]
