# Generated by Django 3.1.5 on 2021-04-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_slide_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='context',
            field=models.TextField(blank=True, null=True, verbose_name='qisa mezmun'),
        ),
    ]
