# Generated by Django 3.1.5 on 2021-04-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_logo_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('context', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='support/')),
            ],
        ),
    ]
