# Generated by Django 3.1.5 on 2021-04-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
