# Generated by Django 3.1.5 on 2021-04-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_statistica'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='context_az',
            field=models.TextField(blank=True, null=True, verbose_name='qisa mezmun'),
        ),
        migrations.AddField(
            model_name='logo',
            name='context_en',
            field=models.TextField(blank=True, null=True, verbose_name='qisa mezmun'),
        ),
        migrations.AddField(
            model_name='logo',
            name='context_ru',
            field=models.TextField(blank=True, null=True, verbose_name='qisa mezmun'),
        ),
        migrations.AddField(
            model_name='slide',
            name='button_name_az',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Linkin adı'),
        ),
        migrations.AddField(
            model_name='slide',
            name='button_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Linkin adı'),
        ),
        migrations.AddField(
            model_name='slide',
            name='button_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Linkin adı'),
        ),
        migrations.AddField(
            model_name='slide',
            name='context_az',
            field=models.TextField(blank=True, null=True, verbose_name='Slayd mətni'),
        ),
        migrations.AddField(
            model_name='slide',
            name='context_en',
            field=models.TextField(blank=True, null=True, verbose_name='Slayd mətni'),
        ),
        migrations.AddField(
            model_name='slide',
            name='context_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Slayd mətni'),
        ),
        migrations.AddField(
            model_name='statistica',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statistica',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statistica',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='context_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='context_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='context_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='description_az',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='description_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='description_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='title_az',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
