# Generated by Django 3.1.5 on 2021-04-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20210419_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='context',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='Slayd mətni'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='context_az',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='Slayd mətni'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='context_en',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='Slayd mətni'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='context_ru',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='Slayd mətni'),
        ),
    ]
